package Component.CSE561project;

import java.awt.*;

import GenCol.doubleEnt;
import view.modeling.*;

public class EF1 extends ViewableDigraph {
	
	public EF1()
	{
		super("Disturbance Experiment");
		addOutport("ClockResult");
		addOutport("DisturbanceResult");
		addOutport("AngleHitResult");
		addOutport("WheelResult");
		
		Satellite satellite = new Satellite();
		Disturbance disturbance = new Disturbance();
		Transducer1 transducer = new Transducer1(300);
		
		add(satellite);
		add(disturbance);
		add(transducer);
		
		addCoupling(disturbance, "SatellitePort", satellite, "ExternalPort");
		addCoupling(disturbance, "SatellitePort", transducer, "DisturbancePort");
		addCoupling(satellite, "Sattelite Angle (degrees)", transducer, "SatellitePortAngle");
		addCoupling(satellite, "Wheel Angular Velocity (RPM)", transducer, "SatellitePortWheel");
		
		addCoupling(transducer, "ClockResult", this, "ClockResult");
		addCoupling(transducer, "DisturbanceResult", this, "DisturbanceResult");
		addCoupling(transducer, "AngleHitResult", this, "AngleHitResult");
		addCoupling(transducer, "WheelResult", this, "WheelResult");
		
		initialize();
	}
	
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(884, 379);
        ((ViewableComponent)withName("Transducer")).setPreferredLocation(new Point(444, 294));
        ((ViewableComponent)withName("Disturbance")).setPreferredLocation(new Point(88, 321));
        ((ViewableComponent)withName("Satellite")).setPreferredLocation(new Point(124, 26));
    }
}
