package Component.CSE561project;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class EF2 extends ViewableDigraph {

	public EF2()
	{
		super("User Command Experiment");
		
		addInport("Start");
		addOutport("Angle");
		addOutport("Rise Time");
		
		Satellite satellite = new Satellite();
		User generator = new User();
		Transducer2 transducer = new Transducer2();
		
		add(satellite);
		add(generator);
		add(transducer);
		
		addCoupling(this, "Start", generator, "Start");
		addCoupling(generator, "Command Out", satellite, "UserPort");
		addCoupling(generator, "Command Out", transducer, "Gen Input");
		addCoupling(satellite, "Sattelite Angle (degrees)", transducer, "Sensor Input");
		addCoupling(satellite, "Sattelite Angle (degrees)", this, "Angle");
		addCoupling(transducer, "Rise Time", this, "Rise Time");
		
		initialize();
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1267, 435);
        ((ViewableComponent)withName("Transducer")).setPreferredLocation(new Point(14, 320));
        ((ViewableComponent)withName("User")).setPreferredLocation(new Point(-1, 109));
        ((ViewableComponent)withName("Satellite")).setPreferredLocation(new Point(223, 42));
    }
}
