package Component.CSE561project;

import java.awt.*;

import GenCol.doubleEnt;
import view.modeling.*;

public class SatelliteEF extends ViewableDigraph {
	
	public SatelliteEF() {this("SatelliteEF");}
	public SatelliteEF(String name)
	{
		super(name);
		
		addInport("UserInput");
		addOutport("Angle");
		addOutport("WheelSpeed");
		addOutport("Disturbance");
		
		Satellite satellite = new Satellite();
		Disturbance disturbance = new Disturbance();
		
		add(satellite);
		add(disturbance);
		
		addCoupling(disturbance, "SensorPort", satellite, "Disturbance In");
		
		addCoupling(this, "UserInput", satellite, "Command In");
		addCoupling(satellite, "Angle Out", this, "Angle");
		addCoupling(satellite, "Wheel Speed Out", this, "WheelSpeed");
		addCoupling(satellite, "Disturbance Out", this, "Disturbance");
		
		initialize();
	}
	
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(884, 379);
        ((ViewableComponent)withName("Disturbance")).setPreferredLocation(new Point(12, 294));
        ((ViewableComponent)withName("Satellite")).setPreferredLocation(new Point(124, 26));
    }
}
