package Component.CSE561project;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class SatelliteEF2 extends ViewableDigraph {

	public SatelliteEF2() {this("SatelliteEF2");}
	public SatelliteEF2(String name)
	{
		super(name);
		
		addInport("Start");
		addOutport("Angle");
		addOutport("Rise Time");
		
		Satellite satellite = new Satellite();
		Generator generator = new Generator();
		Transducer transducer = new Transducer();
		
		add(satellite);
		add(generator);
		add(transducer);
		
		addCoupling(this, "Start", generator, "Start");
		addCoupling(generator, "Command Out", satellite, "UserPort");
		addCoupling(generator, "Command Out", transducer, "Gen Input");
		addCoupling(satellite, "Sattelite Angle (degrees)", transducer, "Sensor Input");
		addCoupling(satellite, "Sattelite Angle (degrees)", this, "Angle");
		addCoupling(transducer, "Rise Time", this, "Rise Time");
		
		initialize();
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(1267, 435);
        ((ViewableComponent)withName("Transducer")).setPreferredLocation(new Point(813, 354));
        ((ViewableComponent)withName("Satellite")).setPreferredLocation(new Point(223, 42));
        ((ViewableComponent)withName("Generator")).setPreferredLocation(new Point(-19, 342));
    }
}
