package Component.CSE561project;

import java.awt.*;

import GenCol.doubleEnt;
import view.modeling.*;

public class SatelliteEF extends ViewableDigraph {
	
	public SatelliteEF() {this("SatelliteEF");}
	public SatelliteEF(String name)
	{
		super(name);
		
		Satellite satellite = new Satellite();
		Disturbance disturbance = new Disturbance();
		
		add(satellite);
		add(disturbance);
		
		addCoupling(disturbance, "SatellitePort", satellite, "ExternalPort");
		
		for(int i=1; i<=8 ;i++)
		{
			double angle = ((double)i/4.0)*Math.PI;
			addTestInput("UserInput", new doubleEnt(angle));
		}
		
		initialize();
	}
	
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(884, 379);
        ((ViewableComponent)withName("Disturbance")).setPreferredLocation(new Point(0, 41));
        ((ViewableComponent)withName("Satellite")).setPreferredLocation(new Point(124, 26));
    }
}
