package Component.CSE561project;

import java.awt.*;

import GenCol.*;
import view.modeling.*;

public class Satellite extends ViewableDigraph {
	
	public Satellite() {this("Satellite");}
	
	public Satellite(String name)	{
		super(name);
		
		addInport("UserPort");
		addInport("ExternalPort");
		
		addOutport("External Torque (Nm)");
		addOutport("Sattelite Angle (degrees)");
		addOutport("Wheel Angular Velocity (RPM)");
		
		Motor motor = new Motor();
		Sensor sensor = new Sensor();
		Controller controller = new Controller();
		
		add(motor);
		add(sensor);
		add(controller);
		
		addCoupling(this, "UserPort", controller, "UserPort");
		addCoupling(this, "ExternalPort", sensor, "ExternalPort");
		
		addCoupling(controller, "MotorPort", motor, "ControllerPort");
		addCoupling(controller, "UserFeedback", this, "Sattelite Angle (degrees)");
		
		addCoupling(motor, "SensorPort", sensor, "MotorPort");
		addCoupling(motor, "UserPort", this, "Wheel Angular Velocity (RPM)");
		
		addCoupling(sensor, "ControllerPortAngle", controller, "SensorPortAngle");
		addCoupling(sensor, "ControllerPortVelocity", controller, "SensorPortVelocity");
		addCoupling(sensor, "UserPort", this, "External Torque (Nm)");
		
		for(int i=1; i<=4 ;i++)	{
			double angle = ((double)i/4.0)*Math.PI;
			addTestInput("UserPort", new doubleEnt(angle));
		}	
		
		initialize();
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView()
    {
        preferredSize = new Dimension(556, 276);
        ((ViewableComponent)withName("Motor")).setPreferredLocation(new Point(-1, 120));
        ((ViewableComponent)withName("Controller")).setPreferredLocation(new Point(34, 34));
        ((ViewableComponent)withName("Sensor")).setPreferredLocation(new Point(29, 188));
    }
}
